# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloudsim_pb2 as cloudsim__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudSimStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/cloud.CloudSim/GetStatus',
                request_serializer=cloudsim__pb2.StatusRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StartNode = channel.unary_unary(
                '/cloud.CloudSim/StartNode',
                request_serializer=cloudsim__pb2.NodeRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.OpResponse.FromString,
                _registered_method=True)
        self.StopNode = channel.unary_unary(
                '/cloud.CloudSim/StopNode',
                request_serializer=cloudsim__pb2.NodeRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.OpResponse.FromString,
                _registered_method=True)
        self.StoreFile = channel.unary_unary(
                '/cloud.CloudSim/StoreFile',
                request_serializer=cloudsim__pb2.StoreFileRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.StoreFileResponse.FromString,
                _registered_method=True)
        self.ReplicateFile = channel.unary_unary(
                '/cloud.CloudSim/ReplicateFile',
                request_serializer=cloudsim__pb2.ReplicateFileRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.OpResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/cloud.CloudSim/ListFiles',
                request_serializer=cloudsim__pb2.UserRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/cloud.CloudSim/GetProfile',
                request_serializer=cloudsim__pb2.UserRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/cloud.CloudSim/DownloadFile',
                request_serializer=cloudsim__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.FileChunk.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/cloud.CloudSim/DeleteFile',
                request_serializer=cloudsim__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.OpResponse.FromString,
                _registered_method=True)
        self.StartNetwork = channel.unary_unary(
                '/cloud.CloudSim/StartNetwork',
                request_serializer=cloudsim__pb2.NetworkRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.OpResponse.FromString,
                _registered_method=True)
        self.StopNetwork = channel.unary_unary(
                '/cloud.CloudSim/StopNetwork',
                request_serializer=cloudsim__pb2.NetworkRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.OpResponse.FromString,
                _registered_method=True)
        self.GetNetworkStatus = channel.unary_unary(
                '/cloud.CloudSim/GetNetworkStatus',
                request_serializer=cloudsim__pb2.StatusRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.NetworkStatusResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/cloud.CloudSim/DeleteNode',
                request_serializer=cloudsim__pb2.NodeRequest.SerializeToString,
                response_deserializer=cloudsim__pb2.OpResponse.FromString,
                _registered_method=True)


class CloudSimServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudSimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=cloudsim__pb2.StatusRequest.FromString,
                    response_serializer=cloudsim__pb2.StatusResponse.SerializeToString,
            ),
            'StartNode': grpc.unary_unary_rpc_method_handler(
                    servicer.StartNode,
                    request_deserializer=cloudsim__pb2.NodeRequest.FromString,
                    response_serializer=cloudsim__pb2.OpResponse.SerializeToString,
            ),
            'StopNode': grpc.unary_unary_rpc_method_handler(
                    servicer.StopNode,
                    request_deserializer=cloudsim__pb2.NodeRequest.FromString,
                    response_serializer=cloudsim__pb2.OpResponse.SerializeToString,
            ),
            'StoreFile': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreFile,
                    request_deserializer=cloudsim__pb2.StoreFileRequest.FromString,
                    response_serializer=cloudsim__pb2.StoreFileResponse.SerializeToString,
            ),
            'ReplicateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateFile,
                    request_deserializer=cloudsim__pb2.ReplicateFileRequest.FromString,
                    response_serializer=cloudsim__pb2.OpResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=cloudsim__pb2.UserRequest.FromString,
                    response_serializer=cloudsim__pb2.ListFilesResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=cloudsim__pb2.UserRequest.FromString,
                    response_serializer=cloudsim__pb2.ProfileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=cloudsim__pb2.DownloadFileRequest.FromString,
                    response_serializer=cloudsim__pb2.FileChunk.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=cloudsim__pb2.DeleteFileRequest.FromString,
                    response_serializer=cloudsim__pb2.OpResponse.SerializeToString,
            ),
            'StartNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.StartNetwork,
                    request_deserializer=cloudsim__pb2.NetworkRequest.FromString,
                    response_serializer=cloudsim__pb2.OpResponse.SerializeToString,
            ),
            'StopNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.StopNetwork,
                    request_deserializer=cloudsim__pb2.NetworkRequest.FromString,
                    response_serializer=cloudsim__pb2.OpResponse.SerializeToString,
            ),
            'GetNetworkStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkStatus,
                    request_deserializer=cloudsim__pb2.StatusRequest.FromString,
                    response_serializer=cloudsim__pb2.NetworkStatusResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=cloudsim__pb2.NodeRequest.FromString,
                    response_serializer=cloudsim__pb2.OpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.CloudSim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.CloudSim', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudSim(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/GetStatus',
            cloudsim__pb2.StatusRequest.SerializeToString,
            cloudsim__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/StartNode',
            cloudsim__pb2.NodeRequest.SerializeToString,
            cloudsim__pb2.OpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/StopNode',
            cloudsim__pb2.NodeRequest.SerializeToString,
            cloudsim__pb2.OpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/StoreFile',
            cloudsim__pb2.StoreFileRequest.SerializeToString,
            cloudsim__pb2.StoreFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/ReplicateFile',
            cloudsim__pb2.ReplicateFileRequest.SerializeToString,
            cloudsim__pb2.OpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/ListFiles',
            cloudsim__pb2.UserRequest.SerializeToString,
            cloudsim__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/GetProfile',
            cloudsim__pb2.UserRequest.SerializeToString,
            cloudsim__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cloud.CloudSim/DownloadFile',
            cloudsim__pb2.DownloadFileRequest.SerializeToString,
            cloudsim__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/DeleteFile',
            cloudsim__pb2.DeleteFileRequest.SerializeToString,
            cloudsim__pb2.OpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/StartNetwork',
            cloudsim__pb2.NetworkRequest.SerializeToString,
            cloudsim__pb2.OpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/StopNetwork',
            cloudsim__pb2.NetworkRequest.SerializeToString,
            cloudsim__pb2.OpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetworkStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/GetNetworkStatus',
            cloudsim__pb2.StatusRequest.SerializeToString,
            cloudsim__pb2.NetworkStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CloudSim/DeleteNode',
            cloudsim__pb2.NodeRequest.SerializeToString,
            cloudsim__pb2.OpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
