# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloudsecurity_pb2 as cloudsecurity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsecurity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/cloudauth.UserService/Login',
                request_serializer=cloudsecurity__pb2.LoginRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.VerifyOtp = channel.unary_unary(
                '/cloudauth.UserService/VerifyOtp',
                request_serializer=cloudsecurity__pb2.VerifyOtpRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.AuthToken.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/cloudauth.UserService/CreateUser',
                request_serializer=cloudsecurity__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/cloudauth.UserService/GetProfile',
                request_serializer=cloudsecurity__pb2.ProfileRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Profile.FromString,
                _registered_method=True)
        self.PrecheckStore = channel.unary_unary(
                '/cloudauth.UserService/PrecheckStore',
                request_serializer=cloudsecurity__pb2.PrecheckStoreRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.PrecheckStoreResponse.FromString,
                _registered_method=True)
        self.AddFileRecord = channel.unary_unary(
                '/cloudauth.UserService/AddFileRecord',
                request_serializer=cloudsecurity__pb2.AddFileRecordRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.AddFileRecordResponse.FromString,
                _registered_method=True)
        self.RemoveFileRecord = channel.unary_unary(
                '/cloudauth.UserService/RemoveFileRecord',
                request_serializer=cloudsecurity__pb2.RemoveFileRecordRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.RemoveFileRecordResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/cloudauth.UserService/ListFiles',
                request_serializer=cloudsecurity__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.ListAllUsers = channel.unary_unary(
                '/cloudauth.UserService/ListAllUsers',
                request_serializer=cloudsecurity__pb2.ListAllUsersRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.ListAllUsersResponse.FromString,
                _registered_method=True)
        self.UpdateUserQuota = channel.unary_unary(
                '/cloudauth.UserService/UpdateUserQuota',
                request_serializer=cloudsecurity__pb2.UpdateUserQuotaRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.UpdateUserQuotaResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOtp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrecheckStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFileRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFileRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=cloudsecurity__pb2.LoginRequest.FromString,
                    response_serializer=cloudsecurity__pb2.LoginResponse.SerializeToString,
            ),
            'VerifyOtp': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOtp,
                    request_deserializer=cloudsecurity__pb2.VerifyOtpRequest.FromString,
                    response_serializer=cloudsecurity__pb2.AuthToken.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=cloudsecurity__pb2.CreateUserRequest.FromString,
                    response_serializer=cloudsecurity__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=cloudsecurity__pb2.ProfileRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Profile.SerializeToString,
            ),
            'PrecheckStore': grpc.unary_unary_rpc_method_handler(
                    servicer.PrecheckStore,
                    request_deserializer=cloudsecurity__pb2.PrecheckStoreRequest.FromString,
                    response_serializer=cloudsecurity__pb2.PrecheckStoreResponse.SerializeToString,
            ),
            'AddFileRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFileRecord,
                    request_deserializer=cloudsecurity__pb2.AddFileRecordRequest.FromString,
                    response_serializer=cloudsecurity__pb2.AddFileRecordResponse.SerializeToString,
            ),
            'RemoveFileRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFileRecord,
                    request_deserializer=cloudsecurity__pb2.RemoveFileRecordRequest.FromString,
                    response_serializer=cloudsecurity__pb2.RemoveFileRecordResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=cloudsecurity__pb2.ListFilesRequest.FromString,
                    response_serializer=cloudsecurity__pb2.ListFilesResponse.SerializeToString,
            ),
            'ListAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllUsers,
                    request_deserializer=cloudsecurity__pb2.ListAllUsersRequest.FromString,
                    response_serializer=cloudsecurity__pb2.ListAllUsersResponse.SerializeToString,
            ),
            'UpdateUserQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserQuota,
                    request_deserializer=cloudsecurity__pb2.UpdateUserQuotaRequest.FromString,
                    response_serializer=cloudsecurity__pb2.UpdateUserQuotaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudauth.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloudauth.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/Login',
            cloudsecurity__pb2.LoginRequest.SerializeToString,
            cloudsecurity__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOtp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/VerifyOtp',
            cloudsecurity__pb2.VerifyOtpRequest.SerializeToString,
            cloudsecurity__pb2.AuthToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/CreateUser',
            cloudsecurity__pb2.CreateUserRequest.SerializeToString,
            cloudsecurity__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/GetProfile',
            cloudsecurity__pb2.ProfileRequest.SerializeToString,
            cloudsecurity__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrecheckStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/PrecheckStore',
            cloudsecurity__pb2.PrecheckStoreRequest.SerializeToString,
            cloudsecurity__pb2.PrecheckStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFileRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/AddFileRecord',
            cloudsecurity__pb2.AddFileRecordRequest.SerializeToString,
            cloudsecurity__pb2.AddFileRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFileRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/RemoveFileRecord',
            cloudsecurity__pb2.RemoveFileRecordRequest.SerializeToString,
            cloudsecurity__pb2.RemoveFileRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/ListFiles',
            cloudsecurity__pb2.ListFilesRequest.SerializeToString,
            cloudsecurity__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/ListAllUsers',
            cloudsecurity__pb2.ListAllUsersRequest.SerializeToString,
            cloudsecurity__pb2.ListAllUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudauth.UserService/UpdateUserQuota',
            cloudsecurity__pb2.UpdateUserQuotaRequest.SerializeToString,
            cloudsecurity__pb2.UpdateUserQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
